### ISSUE TITLE
Warning is not logged for HTML in i18n custom block

### ISSUE THREAD

**Issue by matthew-white** [intlify/vue-i18n-loader#118]
Using the latest version of vue (2.6.11), vue-i18n (8.21.0), and vue-i18n-loader (1.0.0), I think I'm seeing that single file component `i18n` custom blocks do not use the `warnHtmlInMessage` property set on the root `VueI18n` instance.

To reproduce, run `npm run serve` in the following repository:

https://github.com/matthew-white/vue-i18n-repro

Because a message in the `HelloWorld` component contains HTML, I would expect to see a warning logged to the console. However, I do not see a warning.

If `warnHtmlInMessage` is not specified when creating a `VueI18n` instance, then instead of defaulting `warnHtmlInMessage` to `'off'`, I think it would be great if it fell back to the property in the root `VueI18n` instance.

I'm not sure whether this issue belongs here or in https://github.com/kazupon/vue-i18n. However, because it relates to `i18n` custom blocks, I thought I'd file it here.

**Comment by kazupon** [comment]
vue-i18n@v9 or later, check for HTML with `@intlify/core-base`.
