### ISSUE TITLE
Element i18n doesn't have required attribute path

### ISSUE THREAD

**Issue by MBurchard** [intlify/vue-i18n-loader#134]
According to your examples here on GitHub I use this syntax in my Vue components

```
<i18n lang="yml" locale="en">
dismiss_all: Dismiss all
</i18n>

<i18n lang="yml" locale="de">
dismiss_all: Alle entfernen
</i18n>
```

Today I recognized that IntelliJ complains about missing required path attribute.

I use version 1.0.0 of @intlify/vue-i18n-loader.

Maybe there is a invalid dtd somewhere in the package?

**Comment by kazupon** [comment]
close due to in-actvity.
if you would like to continue, you can open the new issue please.

thanks!
