### ISSUE TITLE
can this

### ISSUE THREAD

**Issue by Handandbrainofking** [intlify/vue-i18n-loader#136]
hello，can this loader use in weex project.I found that vue-i18n can use in weex ,but @intlify-i18n-loader can not performace correctly in weex project,weex use "weex-loader",why?

**Comment by kazupon** [comment]
Unfortunately, I don't have the ability to run weex in my environment. So I can't support it.
However, vue-i18n-loader is OSS. If you need it, you can support it by sending a PR.
