### ISSUE TITLE
Not working with `v-t` directive

### ISSUE THREAD

**Issue by theAlexPatin** [intlify/vue-i18n-loader#176]
## Problem

The `v-t` directive only loads the global context. The following code does not work:

```
<i18n locale="en">
{
    "test": "Hello World"
}
</i18n>
<template>
    <p v-t="'test'"></p>
</template>
```

**Comment by kazupon** [comment]
Thank you for your feedback!

I seem that is working in Composition API mode.
if you use Composition API mode, unfortunately, you need to call `useI18n` in `setup`.

**Comment by kazupon** [comment]
clsoe due to in-acticity.
If you would like to continue, you can open the new issue please.

Thanks!
