### ISSUE TITLE
NPM & Github releases totally out-of-sync, releases after 1.1.0 not working with SFC's

### ISSUE THREAD

**Issue by webketje** [intlify/vue-i18n-loader#210]
### Reporting a bug?

The latest version on Github is 2.1.0. The latest version on NPM is 4.1.0. NPM has 9 more versions than Github?? 
Where is their source code? No version after 1.1.0 works with Vue 2.x SFCs (using webpack & vue-loader)
This is very confusing

### Expected behavior

The releases & tags on Github have a 1-on-1 relationship with NPM.
Alternatively a note in the README informs the user about what happened, and which versions are known to work

### Reproduction

Not really a bug, but a request to inform the user

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.44 GB / 15.69 GB
  Binaries:
    Node: 16.13.1 - ~\dev\apps\nvm\v16.13.1\node.EXE
    npm: 8.1.2 - ~\dev\apps\nvm\v16.13.1\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.46)
  npmPackages:
    @intlify/vue-i18n-loader: 1.x.x => 1.1.0
    vue: 2.6.14 => 2.6.14
    vue-i18n: ^8.22.3 => 8.26.8
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-loader/blob/v1.x/.github/CONTRIBUTING.md)
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your feedback
and, sorry for the confusion.

as mentioned about [here](https://github.com/intlify/vue-i18n-loader#warning-notice), this repo is for Vue 2.
Supported version of `@intlify/vue-i18n-loader` for **Vue 2 is v1.1.0**

[Here](https://github.com/intlify/bundle-tools/tree/main/packages/vue-i18n-loader) is the code for `@intlify/vue-i18n-loader` for Vue 3
The latest version at this time that supports Vue 3 is v4.1.0

Thanks!
