### ISSUE TITLE
WebStorm - propper <i18n> block formatting

### ISSUE THREAD

**Issue by irbis999** [intlify/vue-i18n-loader#79]
Hello! 
This is webstorm issue that is connected with the loader.
Webstorm doesn't recognise `<i18n>` block in a single file component and doesn't format in properly. Does somebody know the way to make webstorm format `<i18n>` block as javascript?
https://monosnap.com/file/aWCiDidJ7KARWW9N3SqK0BA28S6Ln9

**Comment by Irevall** [comment]
Try:
Editor -> Language Injections -> XML Tag Injections -> [this](https://i.imgur.com/nomPDQH.png) setting

[Result](https://imgur.com/8CcbXZk.png).

You can set it up the same way if you want to use YAML, although that's [slightly](https://youtrack.jetbrains.com/issue/WEB-43627) bugged.

**Comment by irbis999** [comment]
Thank you!

**Comment by michaelzangl** [comment]
Quick and easy way:

* Place the cursor inside the block, e.g. directly after `<i18n>`
* Hit Alt + Enter
* Select 'Inject language or reference'
* Select 'JSON'

That's it, Webstorm / IntelliJ will apply it to all i18n tags.
