### ISSUE TITLE
DateTime formating without hardcode

### ISSUE THREAD

**Issue by hoangtuan151** [intlify/vue-i18n-loader#81]
Hi guys,

Firstly I want to send many many thanks to the team for your awesome project.

Second, I want to know how to format date time without hardcode:
- Currently, I use this code `this.$d(new Date(), 'short', 'vi-VN')` in Vue methods's scope
- My locale variable is: `this.$i18n.locale = 'vn'`
- I dont want hardcode 'vi-VN' value, so I try `this.$d(new Date(), 'short', this.$i18n.locale)`, but it not worked.
How could I make this code work so that I don't have to hardcode 'vi-VN' value?

Thank in advanced!

**Comment by kazupon** [comment]
Sorry, late for my response.

Could you provide minimue reproduction code, please?

**Comment by kazupon** [comment]
close due to in-activity
