### ISSUE TITLE
When using the custom block, translations in the Vuei18n constructor are gone

### ISSUE THREAD

**Issue by ThaDaVos** [intlify/vue-i18n-loader#83]
Like the title says, when a custom block of `<i18n>` is used in a SFC, the already set translations are gone, for example:

I construct VueI18n as follows:
```JavaScript
new VueI18n({
  locale: 'nl',
  fallbackLocale: 'en',
  messages: {
    nl: {
      hello: 'Hallo!'
    }
  }
})
```

Inside the SFC:
```html
<i18n locale="en">
{
  "hello": "Hello!"
}
</i18n>
<!-- or even: --!>
<i18n>
{
  "en": {
    "hello": "Hello!"
  }
}
</i18n>
```

When you log the following in the mounted hook:
```JavaScript
console.log(this.$i18n.messages);
```
You will notice that only the translations defined inside the custom block are still there, the others, defined in the constructor are gone...

Why is this? Is it possible to have them merged?

**Comment by mathieumagalhaes** [comment]
Have you found any workaround for this use-case?

**Comment by kazupon** [comment]
Sorry, late for my response.

This is specification.
If there is an i18n custom block in the component, that resource takes precedence.
If the key specified in `$ t` or` t` does not exist in the component's i18n cusom block, fallback to global resource.
