### ISSUE TITLE
$t cannot translate the global value when I have a locel i18n block in component

### ISSUE THREAD

**Issue by linlinyang** [intlify/vue-i18n-loader#85]
![image](https://user-images.githubusercontent.com/12453585/75842926-b7884100-5e0c-11ea-8f97-8c36c218134b.png)

the $('title') I has defined in global and if I delete this i18n block,the global variables can translate.
if i add this i18n block and then the locale can work but the global fail.

and my webpack config is :
![image](https://user-images.githubusercontent.com/12453585/75842903-a7706180-5e0c-11ea-8c45-36e8a6df20e1.png)

in my webpack.config.js

**Comment by sefacndmr01** [comment]
Hi @linlinyang, how did you solve this issue? Can you explain?
