### ISSUE TITLE
Are there any breaking changes in v1.0.0?

### ISSUE THREAD

**Issue by rchl** [intlify/vue-i18n-loader#90]
The version has jumped from 0.6.x to 1.0.0. Does that mean that the package is now considered stable or there are major changes since 0.6.x?

I feel like I know the answer by looking at the code but I'd like to have confirmation.

**Comment by kazupon** [comment]
There is not breaking change in v1.0.0
The meaning of this release is that it's stable, and that it would like to tweak the version for Vue 3.
